name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build

      - name: Make Windows Build
        run: npm run make -- --platform=win32

      - name: Upload Windows Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            out/make/squirrel.windows/x64/Glint*.exe
            out/make/squirrel.windows/x64/Glint*.nupkg
            out/make/squirrel.windows/x64/RELEASES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build

      - name: Make macOS Build
        run: npm run make -- --platform=darwin

      - name: Upload macOS Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            out/make/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 